name: create_issue

on:
  repository_dispatch:
    types: [issue]

jobs:
  terraform:
    name: "Create Issue"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: payload
      run: echo ${{github.event.client_payload.user}} ${{github.event.client_payload.action}}
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: a
        ACTION: b
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    # - name: Configure AWS credentials
    #   id: aws_credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: ${{ env.TERRAFORM_ROLE }}
    #     aws-region: ${{ env.AWS_DEFAULT_REGION }}
    # - name: Terraform Init
    #   id: init
    #   run: terraform init
    # - name: Terraform Import
    #   id: import
    #   run: terraform plan -no-color -input=false -refresh-only
    
