name: terraform_import

on:
  repository_dispatch:
    types: [import]

env:
  TERRAFORM_ROLE: arn:aws:iam::956204488690:role/terraform-administrator-role
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    name: "Terraform Import"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: payload
      run: echo ${{github.event.client_payload}}
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    # - name: Configure AWS credentials
    #   id: aws_credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: ${{ env.TERRAFORM_ROLE }}
    #     aws-region: ${{ env.AWS_DEFAULT_REGION }}
    # - name: Terraform Init
    #   id: init
    #   run: terraform init
    # - name: Terraform Import
    #   id: import
    #   run: terraform plan -no-color -input=false -refresh-only
    
